<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="assets/script.js"></script>
    <script src="websys.json"></script>
</head>
<body>
<div class="d-flex align-items-start">
  <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link active" id="v-pills-lec1-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec1" type="button" role="tab" aria-controls="v-pills-lec1" aria-selected="true">Lecture 1</button>
    <button class="nav-link" id="v-pills-lec2-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec2" type="button" role="tab" aria-controls="v-pills-lec2" aria-selected="false">Lecture 2</button>
    <button class="nav-link" id="v-pills-lec3-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec3" type="button" role="tab" aria-controls="v-pills-lec3" aria-selected="false">Lecture 3</button>
    <button class="nav-link" id="v-pills-lec4-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec4" type="button" role="tab" aria-controls="v-pills-lec4" aria-selected="false">Lecture 4</button>
    <button class="nav-link" id="v-pills-lec5-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec5" type="button" role="tab" aria-controls="v-pills-lec5" aria-selected="false">Lecture 5</button>
    <button class="nav-link" id="v-pills-lec6-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec6" type="button" role="tab" aria-controls="v-pills-lec6" aria-selected="false">Lecture 6</button>
    <button class="nav-link" id="v-pills-lec7-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec7" type="button" role="tab" aria-controls="v-pills-lec7" aria-selected="false">Lecture 7</button>
    <button class="nav-link" id="v-pills-lec8-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec8" type="button" role="tab" aria-controls="v-pills-lec8" aria-selected="false">Lecture 8</button>
    <button class="nav-link" id="v-pills-lec9-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec9" type="button" role="tab" aria-controls="v-pills-lec9" aria-selected="false">Lecture 9</button>
    <button class="nav-link" id="v-pills-lec10-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec10" type="button" role="tab" aria-controls="v-pills-lec10" aria-selected="false">Lecture 10</button>
    <button class="nav-link" id="v-pills-lec11-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec11" type="button" role="tab" aria-controls="v-pills-lec11" aria-selected="false">Lecture 11</button>
    <button class="nav-link" id="v-pills-lec12-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec12" type="button" role="tab" aria-controls="v-pills-lec12" aria-selected="false">Lecture 12</button>
    <button class="nav-link" id="v-pills-lec13-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec13" type="button" role="tab" aria-controls="v-pills-lec13" aria-selected="false">Lecture 13</button>
    <button class="nav-link" id="v-pills-lec14-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec14" type="button" role="tab" aria-controls="v-pills-lec14" aria-selected="false">Lecture 14</button>
    <button class="nav-link" id="v-pills-lec15-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lec15" type="button" role="tab" aria-controls="v-pills-lec15" aria-selected="false">Lecture 15</button>
    <button class="nav-link" id="v-pills-lab1-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab1" type="button" role="tab" aria-controls="v-pills-lab1" aria-selected="false">Lab 1</button>
    <button class="nav-link" id="v-pills-lab2-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab2" type="button" role="tab" aria-controls="v-pills-lab2" aria-selected="false">Lab 2</button>
    <button class="nav-link" id="v-pills-lab3-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab3" type="button" role="tab" aria-controls="v-pills-lab3" aria-selected="false">Lab 3</button>
    <button class="nav-link" id="v-pills-lab4-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab4" type="button" role="tab" aria-controls="v-pills-lab4" aria-selected="false">Lab 4</button>
    <button class="nav-link" id="v-pills-lab5-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab5" type="button" role="tab" aria-controls="v-pills-lab5" aria-selected="false">Lab 5</button>
    <button class="nav-link" id="v-pills-lab6-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab6" type="button" role="tab" aria-controls="v-pills-lab6" aria-selected="false">Lab 6</button>
    <button class="nav-link" id="v-pills-lab7-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab7" type="button" role="tab" aria-controls="v-pills-lab7" aria-selected="false">Lab 7</button>
    <button class="nav-link" id="v-pills-lab8-tab" data-bs-toggle="pill" data-bs-target="#v-pills-lab8" type="button" role="tab" aria-controls="v-pills-lab8" aria-selected="false">Lab 8</button>
  </div>
  <div class="tab-content" id="v-pills-tabContent">
    <div class="tab-pane fade show active" id="v-pills-lec1" role="tabpanel" aria-labelledby="v-pills-home-tab">The Basics<br>This lecture covers the basics needed to understand the content covered in Web Systems Development.\\nEverything from setting up AMP stacks to HTTP Status codes are covered.<br><a href="https://docs.google.com/presentation/d/1gvCq-nWWM4ggARP6liG94KJZeRBpaNoRm9CkmxbzWT0/edit?usp=sharing">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec2" role="tabpanel" aria-labelledby="v-pills-profile-tab">Git and Apache<br>This lecture goes over the basics of Github and Apache servers.<br><a href="https://docs.google.com/presentation/d/1ha7ZyL1FMxKoo43iFNoMByP00z7l9nTH7UMWcmH-4Tg/edit?usp=sharing">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec3" role="tabpanel" aria-labelledby="v-pills-messages-tab">HTML 5<br>This lecture covers the history and basics of Hypertext Markup Language (HTML) and Extensible Markup Language (XML).<br><a href="https://drive.google.com/file/d/1YgLfeYeVHrgy5aMfFFw5Z1cNENaHkpyV/view">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec4" role="tabpanel" aria-labelledby="v-pills-settings-tab">CSS<br>This lecture covers the basics of Cascading Style Sheets (CSS)<br><a href="https://docs.google.com/presentation/d/1usbhG9skLKmKpiMtA7udt36f2mzbscXT/edit?usp=sharing&amp;ouid=101431771635793895949&amp;rtpof=true&amp;sd=true">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec5" role="tabpanel" aria-labelledby="v-pills-settings-tab">Advanced CSS<br>This lecture covers more advanced CSS features such as animations, combinators, and frameworks.<br><a href="https://docs.google.com/presentation/d/1Vp_-_fqCBtwhlgT3HhqMbXx-7Piv7OPiQvblxyznPZE/edit?usp=sharing">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec6" role="tabpanel" aria-labelledby="v-pills-settings-tab">Javascript<br>This lecture coves the basics of Javascript.<br><a href="https://docs.google.com/presentation/d/108yq32gLsn9Dn6_pjdpku9YagWjpaDuVY86BHfCB1KM/edit#slide=id.g478b47820c_0_56">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec7" role="tabpanel" aria-labelledby="v-pills-settings-tab">AJAX and JSON<br>This lecture covers the basics of both AJAX and JSON.<br><a href="https://docs.google.com/presentation/d/1CuKTZPsaJQs1DRgKbKHlObP_rTXv0HtAhm_wLFpEYfM/edit#slide=id.p">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec8" role="tabpanel" aria-labelledby="v-pills-settings-tab">jQuery<br>This lecture covers the basics of jQuery.<br><a href="https://docs.google.com/presentation/d/1TOpBmwdZF1cUNfzcZ8t2DT237vvm5yFnqqi9mUzNBYw/edit#slide=id.p">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec9" role="tabpanel" aria-labelledby="v-pills-settings-tab">Front End Optimization<br>This lecture covers front end optimizations that can improve the performance of a website or web resource.<br><a href="https://docs.google.com/presentation/d/1xnWSdl3QlAJhhYZJB-L9qulDC2VGb67Ye5jGF5A0NTk/edit#slide=id.p">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec10" role="tabpanel" aria-labelledby="v-pills-settings-tab">PHP<br>This lecture covers the basics of PHP.<br><a href="https://docs.google.com/presentation/d/1FQrs6bCzF6lyfCXYm--leU81zl9uMwLz/edit?amp;ouid=101431771635793895949&amp;rtpof=true&amp;sd=true#slide=id.p1">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec11" role="tabpanel" aria-labelledby="v-pills-settings-tab">PHP, The Sequel<br>This lecture covers further delves into more PHP features and concepts like interfaces, abstract classes, and polymorphism.<br><a href="https://docs.google.com/presentation/d/1l-idKFz6MG4l057y9kiz_aSMUcEIwJRnZvi88UBUB98/edit?usp=sharing">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec12" role="tabpanel" aria-labelledby="v-pills-settings-tab">MySQL<br>This lecture covers the basics of MySQL.<br><a href="https://docs.google.com/presentation/d/1b9FUdOQxXLWUB_tNlShdqN695tt8nwMh/edit?usp=sharing&amp;ouid=101431771635793895949&amp;rtpof=true&amp;sd=true">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec13" role="tabpanel" aria-labelledby="v-pills-settings-tab">PHP and MySQL<br>This lecture covers using PHP with MySQL queries, databases, and APIs.<br><a href="https://docs.google.com/presentation/d/1hdchGQdRVq_vmLc4Ot1TbyDADWahZ15f/edit?amp;ouid=101431771635793895949&amp;rtpof=true&amp;sd=true#slide=id.p1">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec14" role="tabpanel" aria-labelledby="v-pills-settings-tab">PHP and MySQL (part 2)<br>This lecture is a continuation of lecture 13 (PHP & MySQL).<br><a href="https://docs.google.com/presentation/d/1hdchGQdRVq_vmLc4Ot1TbyDADWahZ15f/edit?amp;ouid=101431771635793895949&amp;rtpof=true&amp;sd=true#slide=id.p1">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lec15" role="tabpanel" aria-labelledby="v-pills-settings-tab">Authorization and Looking Ahead<br>This lecture covers authentication and authorization as well as a brief overview of the content covered \\nin Web Science Systems Development.<br><a href="https://docs.google.com/presentation/d/1IVV09GiwEho8KN4j3XFa9oVdIkz1t9LW/edit?usp=sharing&amp;ouid=101431771635793895949&amp;rtpof=true&amp;sd=true">Link to Lecture</a></div>
    <div class="tab-pane fade" id="v-pills-lab1" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 1<br>This lab will have you create a portfolio website for your group, which will include a portfolio site/page for each individual member of the group within.<br><a href="https://docs.google.com/document/d/1gfBFgyWVZ4HrudNXn4h_TCicEtdywLBdQxfIEZl-U98/edit">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab2" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 2<br>With your group, create a Constitution Day web application. Choose a target audience and tailor your web application\\nto them. Remember to make your site accessible.<br><a href="https://docs.google.com/document/d/1oOEMKBc2Dq6C69Y_pkXRipkVYB5-b-UskvswnTOiNV0/edit?usp=sharing">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab3" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 3<br>Make a new website for ITWS. The website should contain general information about the major and core faculty as well as\\ncontact information, social media links, and related news.<br><a href="https://docs.google.com/document/d/1TAqC_JIZ70o3bf87aCTPtFJxXB4k-VSQzesWzNDsMJI/edit?usp=sharing">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab4" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 4<br>Create a new website for Gamma Nu Eta. Only HTML5, CSS3, and JS may be used. A homepage and an events/activities page must be present.\\nBranding material provided must be used.\\nContent that appears on more than one page was must be turned into a JSON object.<br><a href="https://docs.google.com/document/d/1VBy44Ts1Zly14JJPiFk1LeQnqEVVVHxbZQJzgRjrVfo/edit?usp=sharing">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab5" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 5<br>Optimize the 'Free Bee' web application. At least 7 optimizations must be implemented. Game logic must not\\nbe changed. Improvements to layout and design are allowed.<br><a href="https://docs.google.com/document/d/19fi99OeR6RFPDIMtio7xAyk7EkbvWlhiQzxi5LrS8hs/edit?usp=sharing">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab6" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 6<br>Create a simple calculator using PHP. The program must include interfaces, abstract classes, and polymorphism.\\nHTML, CSS, and JS are optional.<br><a href="https://docs.google.com/document/d/1Aur3WmROp_lYT6UIIs1HjlZrc450VoORUXVzrXajZ8c/edit?usp=sharing">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab7" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 7<br>Use PHP to create a simple gradebook. Use MySQL to create databases that can be altered by the web application.\\nList all commands used for Parts 1 and 2 of your web application in your Github ReadMe.<br><a href="https://docs.google.com/document/d/1ILpyD9LtNgXQ_g8-9bNV9DOgjZkL25Nup69x2wX0dHg/edit?usp=sharing">Link to Lab</a></div>
    <div class="tab-pane fade" id="v-pills-lab8" role="tabpanel" aria-labelledby="v-pills-settings-tab">Lab 8<br>Create a web application that uses utilizes JSON to dynamically display content. The web app must include a login page and a database for access.<br><a href="https://docs.google.com/document/d/1SIF9NwMwpI3HgYLhjoM0kAUpI5Pwp2-QefjjfE3FxBo/edit">Link to Lab</a></div>
  </div>
</div>
<button>Refresh</button>
<button>Log out</button>
</body>
</html>